import "server-only";

import { SupabaseClient } from "@supabase/supabase-js";
import "./globals.css";
import { Providers } from "./providers";
import { Database } from "types/supabase";
import { createServerClient } from "components/supabase-server";
import SupabaseProvider from "components/supabase-provider";
import SupabaseListener from "components/supabase-listener";
import { ComposedNavbar } from "components/navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type TypedSupabaseClient = SupabaseClient<Database>;

// do not cache this layout
export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <head />
      <body className="light">
        <Providers>
          <SupabaseProvider session={session}>
            <SupabaseListener serverAccessToken={session?.access_token} />
            <ComposedNavbar />
            <main className="min-h-screen bg-neutral-900 flex flex-col items-center">
              {children}
            </main>
          </SupabaseProvider>
        </Providers>
      </body>
    </html>
  );
}
