import "server-only";

import { SupabaseClient } from "@supabase/supabase-js";
import "./globals.css";
import { Providers } from "./providers";
import { Database } from "types/supabase";
import { createServerClient } from "components/supabase-server";
import SupabaseProvider from "components/supabase-provider";
import SupabaseListener from "components/supabase-listener";
import { ComposedNavbar } from "components/navbar/Navbar";
import { ConfirmModal } from "components/modals/ConfirmModal";
import ConfirmContextProvider from "providers/ConfirmContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type TypedSupabaseClient = SupabaseClient<Database>;

// do not cache this layout
export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <head />
      <body className="light">
        <Providers>
          <ConfirmContextProvider>
            <SupabaseProvider session={session}>
              <SupabaseListener serverAccessToken={session?.access_token} />
              <ComposedNavbar />
              <ConfirmModal />
              <main className="mt-20 min-h-screen bg-neutral-900 flex flex-col items-center">
                {children}
              </main>
            </SupabaseProvider>
          </ConfirmContextProvider>
        </Providers>
      </body>
    </html>
  );
}
